<?php

return [
    'about_pages' => [
        'coway-story' => [
            'slug' => 'coway-story',
            'nav' => 'Story',
            'title' => 'Coway Story',
            'kicker' => 'Tentang Coway',
            'description' => 'Perjalanan Coway berawal dari keyakinan bahwa kualitas hidup dapat ditingkatkan melalui air, udara, dan lingkungan rumah yang lebih sehat.',
            'image' => 'https://cowayjkt.id/wp-content/uploads/2022/03/our-story-bg-xs.webp',
            'source' => 'https://cowayjkt.id/about-coway/coway-story/',
            'sections' => [
                ['title' => 'Perjalanan untuk kehidupan yang lebih baik', 'copy' => 'Coway terus mencari kemungkinan baru, solusi baru, dan permulaan baru agar produk kesehatan rumah dapat memberi nilai nyata bagi generasi sekarang dan berikutnya.'],
                ['title' => 'Pure Way of Life', 'copy' => 'Fokus Coway ada pada pengalaman hidup yang lebih bersih, aman, dan nyaman melalui teknologi pemurnian air, udara, dan layanan perawatan pelanggan.'],
                ['title' => 'Nilai untuk tim penjualan', 'copy' => 'Cerita Coway membantu sales menjelaskan bahwa produk bukan hanya perangkat rumah, tetapi bagian dari gaya hidup sehat yang didukung inovasi berkelanjutan.'],
            ],
            'highlights' => ['Solusi lingkungan rumah', 'Inovasi berkelanjutan', 'Kualitas hidup pelanggan'],
        ],
        'market-share' => [
            'slug' => 'market-share',
            'nav' => 'Market Share',
            'title' => 'Market Share',
            'kicker' => 'Pangsa Pasar',
            'description' => 'Coway dikenal sebagai salah satu pemimpin industri pemurni air dan pemurni udara, dengan pengakuan dari konsumen dan pakar di Korea maupun Indonesia.',
            'image' => 'https://cowayjkt.id/wp-content/uploads/2022/03/market-share-bg-xs.webp',
            'source' => 'https://cowayjkt.id/about-coway/market-share/',
            'sections' => [
                ['title' => 'Kepercayaan pasar', 'copy' => 'Reputasi Coway dibangun melalui kualitas produk, layanan berkelanjutan, dan konsistensi dalam menghadirkan teknologi pemurnian untuk rumah modern.'],
                ['title' => 'Pemimpin kategori', 'copy' => 'Dalam percakapan sales, posisi Coway sebagai merek kuat di kategori water purifier dan air purifier dapat menjadi bukti kredibilitas produk.'],
                ['title' => 'Daya dukung penjualan', 'copy' => 'Informasi market share membantu tim menjawab keberatan pelanggan dengan narasi yang lebih meyakinkan dan berbasis reputasi merek.'],
            ],
            'highlights' => ['Water purifier', 'Air purifier', 'Kepercayaan konsumen'],
        ],
        'coway-history' => [
            'slug' => 'coway-history',
            'nav' => 'History',
            'title' => 'Coway History',
            'kicker' => 'Sejarah Coway',
            'description' => 'Sejarah Coway dibentuk oleh riset, pengembangan, dan komitmen pada solusi lingkungan yang mendukung kesehatan dan kesejahteraan.',
            'image' => 'https://cowayjkt.id/wp-content/uploads/2022/03/our-history-bg-xs.jpg',
            'source' => 'https://cowayjkt.id/about-coway/coway-history/',
            'sections' => [
                ['title' => 'Tumbuh melalui inovasi', 'copy' => 'Coway berkembang dengan spesialis dan ilmuwan yang meneliti teknologi pemurnian, memperluas produk, dan menjaga standar kualitas dari waktu ke waktu.'],
                ['title' => 'Konsistensi layanan', 'copy' => 'Jejak sejarah Coway memperlihatkan bahwa layanan aftersales dan pengelolaan produk menjadi bagian penting dari pengalaman pelanggan.'],
                ['title' => 'Fondasi brand', 'copy' => 'Riwayat perusahaan menjadi bahan cerita untuk memperkuat kepercayaan pelanggan terhadap stabilitas dan pengalaman Coway.'],
            ],
            'highlights' => ['Riset jangka panjang', 'Teknologi lingkungan', 'Brand global'],
        ],
        'coway-research-development' => [
            'slug' => 'coway-research-development',
            'nav' => 'Research & Development',
            'title' => 'Coway Research & Development',
            'kicker' => 'Inovasi dan Pengujian',
            'description' => 'Pusat R&D Coway mendukung pengembangan produk dengan fasilitas, pengujian, dan standar kualitas untuk menghadirkan air dan udara yang lebih baik.',
            'image' => 'https://cowayjkt.id/wp-content/uploads/2025/10/coway-research-centre.webp',
            'source' => 'https://cowayjkt.id/about-coway/coway-research-development/',
            'sections' => [
                ['title' => 'Pusat riset bersertifikasi', 'copy' => 'Coway menempatkan riset sebagai fondasi produk, termasuk pengujian kualitas air, filtrasi, material, dan performa teknologi pemurnian.'],
                ['title' => 'Peralatan mutakhir', 'copy' => 'Referensi Coway JKT menyebut R&D Center bersertifikat WQA dan dilengkapi banyak perangkat pengujian untuk menjaga kualitas produk.'],
                ['title' => 'Manfaat untuk pelanggan', 'copy' => 'Penjelasan R&D membantu pelanggan memahami bahwa desain produk Coway berasal dari proses validasi yang serius, bukan sekadar tampilan.'],
            ],
            'highlights' => ['WQA', 'Pengujian kualitas', 'Inovasi produk'],
        ],
        'design-philosophy' => [
            'slug' => 'design-philosophy',
            'nav' => 'Design Philosophy',
            'title' => 'Design Philosophy',
            'kicker' => 'Filosofi Desain',
            'description' => 'Coway menggunakan desain sebagai alat untuk menyediakan produk dan layanan terbaik yang mencerminkan budaya masa depan.',
            'image' => 'https://cowayjkt.id/wp-content/uploads/2022/03/design-philosophy-bg-xs.jpg',
            'source' => 'https://cowayjkt.id/about-coway/design-philosophy/',
            'sections' => [
                ['title' => 'Desain untuk kehidupan modern', 'copy' => 'Produk Coway dirancang agar mudah digunakan, mudah dirawat, dan cocok ditempatkan di berbagai interior rumah modern.'],
                ['title' => 'Fungsi yang terasa alami', 'copy' => 'Filosofi desain Coway menyeimbangkan teknologi, kenyamanan, dan bentuk yang bersih sehingga produk terasa menjadi bagian dari rumah.'],
                ['title' => 'Nilai visual saat presentasi', 'copy' => 'Bagi sales, desain adalah pintu masuk untuk menjelaskan manfaat produk secara emosional dan praktis sekaligus.'],
            ],
            'highlights' => ['Minimal', 'Fungsional', 'Modern'],
        ],
        'corporate-customers' => [
            'slug' => 'corporate-customers',
            'nav' => 'Corporate Customers',
            'title' => 'Corporate Customers',
            'kicker' => 'Pelanggan Korporat',
            'description' => 'Berbagai perusahaan dan instansi pemerintah telah mempercayakan solusi penyaringan udara dan air kepada Coway.',
            'image' => 'https://cowayjkt.id/wp-content/uploads/2022/03/csr-trust-bg.webp',
            'source' => 'https://cowayjkt.id/about-coway/corporate-customers/',
            'sections' => [
                ['title' => 'Solusi untuk lingkungan kerja', 'copy' => 'Produk Coway dapat mendukung kantor, area layanan, dan ruang komersial yang membutuhkan kualitas air dan udara yang terjaga.'],
                ['title' => 'Kepercayaan skala bisnis', 'copy' => 'Pelanggan korporat menjadi bukti bahwa Coway tidak hanya relevan untuk rumah, tetapi juga untuk kebutuhan organisasi.'],
                ['title' => 'Bahan komunikasi B2B', 'copy' => 'Tim sales dapat memakai narasi corporate customer saat berdiskusi dengan prospek perusahaan, kantor, dan komunitas.'],
            ],
            'highlights' => ['Kantor', 'Komersial', 'B2B'],
        ],
        'corporate-social-responsibility' => [
            'slug' => 'corporate-social-responsibility',
            'nav' => 'Corporate Social Responsibility',
            'title' => 'Corporate Social Responsibility',
            'kicker' => 'Tanggung Jawab Sosial',
            'description' => 'CSR Coway mencerminkan kepedulian perusahaan terhadap masyarakat, lingkungan, dan kualitas hidup yang lebih baik.',
            'image' => 'https://cowayjkt.id/wp-content/uploads/2022/03/csr-leading-bg.webp',
            'source' => 'https://cowayjkt.id/about-coway/corporate-social-responsibility/',
            'sections' => [
                ['title' => 'Kontribusi sosial', 'copy' => 'Coway menghubungkan bisnis dengan kepedulian sosial melalui inisiatif yang mendukung kesehatan, lingkungan, dan kesejahteraan masyarakat.'],
                ['title' => 'Brand yang bertanggung jawab', 'copy' => 'Program sosial membantu memperlihatkan bahwa Coway tidak hanya menjual produk, tetapi juga membawa misi kehidupan yang lebih baik.'],
                ['title' => 'Cerita untuk membangun trust', 'copy' => 'CSR dapat digunakan sales untuk menunjukkan sisi humanis dan komitmen jangka panjang Coway terhadap pelanggan dan lingkungan.'],
            ],
            'highlights' => ['Masyarakat', 'Lingkungan', 'Kesejahteraan'],
        ],
        'halal' => [
            'slug' => 'halal',
            'nav' => 'Halal',
            'title' => 'Halal',
            'kicker' => 'Sertifikasi dan Kepercayaan',
            'description' => 'Coway dikenal sebagai merek pemurni air internasional pertama yang bersertifikat Halal, termasuk bagian mesin dan filter tertentu pada pemurni air Coway.',
            'image' => 'https://cowayjkt.id/wp-content/uploads/2023/01/coway-halal-certified-water-purifiers.webp',
            'source' => 'https://cowayjkt.id/about-coway/halal/',
            'sections' => [
                ['title' => 'Keyakinan pelanggan', 'copy' => 'Topik halal penting untuk memberi rasa aman bagi pelanggan yang mempertimbangkan standar produk sebelum melakukan pembelian.'],
                ['title' => 'Dukungan untuk pasar Indonesia', 'copy' => 'Dengan menampilkan informasi halal, tim dapat menjawab kebutuhan konsumen lokal secara lebih siap dan jelas.'],
                ['title' => 'Percakapan yang lebih mudah', 'copy' => 'Halaman ini membantu sales membuka diskusi tentang standar, kualitas, dan kepercayaan produk Coway.'],
            ],
            'highlights' => ['Standar pelanggan', 'Pasar Indonesia', 'Kepercayaan'],
        ],
    ],
];
